services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        https_proxy: ${https_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        no_proxy: ${no_proxy}
        NO_PROXY: ${NO_PROXY}
    volumes:
      - .:/app:cached
    depends_on:
      - localstack
    command: sleep infinity
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566            
      - 4510-4559:4510-4559  # external services port range
    environment:
      - SERVICES=logs,lambda,apigateway,s3,cloudformation,iam,secretsmanager,dynamodb
    env_file:
      - .env
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]


volumes:
  localstack_data: 