service: hono-lambda-dynamodb

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_DEFAULT_REGION}
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: ${env:AWS_DEFAULT_REGION}
    DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    TABLE_NAME: ${env:TABLE_NAME}
    SERVER_HOST: ${env:SERVER_HOST}
    SAM_CLI_TELEMETRY: ${env:SAM_CLI_TELEMETRY}
    API_BASE_URL: ${env:API_BASE_URL}
    API_VERSION: ${env:API_VERSION}
    API_KEY: ${env:API_KEY}
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    host: ${env:SERVER_HOST, '127.0.0.1'}
    format: esm
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude:
      - aws-sdk
      - '@aws-sdk/*'
    platform: 'node'
    target: 'node20'
    outputWorkFolder: 'dist'
    format: esm
    external:
      - '@aws-sdk/*'
