AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${env:AWS_DEFAULT_REGION}
        DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
        TABLE_NAME: ${env:TABLE_NAME}
        SERVER_HOST: ${env:SERVER_HOST}
        SAM_CLI_TELEMETRY: ${env:SAM_CLI_TELEMETRY}
        API_BASE_URL: ${env:API_BASE_URL}
        API_VERSION: ${env:API_VERSION}
        API_KEY: ${env:API_KEY}
        ACCESS_TOKEN: ${env:ACCESS_TOKEN}
  Api:
    OpenApiVersion: '2.0'

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: hono-lambda-dynamodb:latest
      Architectures:
        - arm64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: nodejs20.x-v1

Parameters:
  Stage:
    Type: String
    Default: dev

Metadata:
  AWS::SAM::Cli:
    DockerNetwork: hono-lambda-dynamodb_devcontainer_dev-network
