AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LocalStack+SAM

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction
      Handler: src/lambda.handler
      CodeUri: ./src
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
          EDGE_PORT: 4566
          DYNAMODB_TABLE_ISSUER: ISSUER_SESSION_DYNAMO
          DYNAMODB_ENDPOINT: http://localstack:4566
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  IssuerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ISSUER_SESSION_DYNAMO
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
