name = "vc-issuer"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public/" }

# [vars]
# MY_VAR = "my-variable"

# KV Namespaces
# For local development, create your own KV namespaces and set the IDs as environment variables:
# export SESSION_KV_ID=your_session_kv_id
# export USER_KV_ID=your_user_kv_id
# export MDOC_KV_ID=your_mdoc_kv_id
#
# Or create a .env.local file with these variables

[[kv_namespaces]]
binding = "SESSION_KV"
id = "${SESSION_KV_ID}"
[[kv_namespaces]]
binding = "USER_KV"
id = "${USER_KV_ID}"
[[kv_namespaces]]
binding = "MDOC_KV"
id = "${MDOC_KV_ID}"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
