name = "vc-issuer"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public/" }

# [vars]
# MY_VAR = "my-variable"

# KV Namespaces
# These use environment variables for the IDs to allow sharing wrangler.toml
# while keeping local KV namespace IDs separate.
#
# For local development:
# 1. Create your own KV namespaces: npx wrangler kv namespace create
# 2. Create a .env.local file with the KV namespace IDs:
#    SESSION_KV_ID=your_session_kv_id
#    USER_KV_ID=your_user_kv_id
#    MDOC_KV_ID=your_mdoc_kv_id
#
# Wrangler will automatically load .env.local and use these environment variables

[[kv_namespaces]]
binding = "SESSION_KV"
id = "SESSION_KV_ID_PLACEHOLDER"
[[kv_namespaces]]
binding = "USER_KV"
id = "USER_KV_ID_PLACEHOLDER"
[[kv_namespaces]]
binding = "MDOC_KV"
id = "MDOC_KV_ID_PLACEHOLDER"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
