name = "vc-issuer"
compatibility_date = "2024-10-25"
compatibility_flags = [ "nodejs_compat" ]
assets = { directory = "./public/" }

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "76142d27e3b744ce949e81f45ebc2e28"
[[kv_namespaces]]
binding = "USER_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
[[kv_namespaces]]
binding = "MDOC_KV"
id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true